spring.datasource.url=jdbc:postgresql://localhost:5432/leetcodeai
spring.datasource.username=postgres
spring.datasource.password=raunak216

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
gemini.api.key=AIzaSyAvyHmkEBv2qFhuc38thzEUWGqxBWBMTvA